import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import FloatingButton from '../components/FloatingButton';
import TextEditor from '../components/TextEditor';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <TextEditor />
        <FloatingButton />
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
