import React from 'react';
import Head from 'next/head';
import { TextField, Grid, Typography, Button } from '@mui/material';
import Header from '../components/Header';
import Footer from '../components/Footer';

export default function Home() {

  const [username, setUsername] = React.useState("");
  const [password, setPassword] = React.useState("");

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
      <form>
          <Grid
            container
            direction="column"
            justifyContent="center"
            alignItems="center"
            spacing={3}
          >
            <Grid item>
              <Typography variant="h5"><b>Login</b></Typography>
            </Grid>
            <Grid item>
              <TextField
                label="Usuário"
                variant="filled"
                type="text"
                name="username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
            </Grid>
            <Grid item>
              <TextField
                label="Senha"
                variant="filled"
                type="password"
                name="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </Grid>
            <Grid item>
              <Button sx={{ backgroundColor: "#082947ff" }} type="submit">ENTRAR</Button>
            </Grid>
            <Grid item>
              <Typography variant="p">
                <a href='/forgot-password'>Esqueci a senha</a> | <a href='/signup'>Cadastre-se</a>
              </Typography>
            </Grid>
          </Grid>
        </form>
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  )
}
