import React from 'react';
import Head from 'next/head';
import { TextField, Grid, Typography, Button } from '@mui/material';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

export default function SignUp() {

  const [username, setUsername] = React.useState("");
  const [password, setPassword] = React.useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
      <form>
          <Grid
            container
            direction="column"
            justifyContent="center"
            alignItems="center"
            spacing={3}
          >
            <Grid item>
              <Typography variant="h5"><b>Registrar-se</b></Typography>
            </Grid>
            <Grid item>
              <TextField
              required
                label="Usuário"
                variant="filled"
                type="text"
                name="username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
            </Grid>
            <Grid item>
              <TextField
              required
                label="Senha"
                variant="filled"
                type="password"
                name="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </Grid>
            <Grid item>
              <Button type="submit">Confirmar</Button>
            </Grid>
          </Grid>
        </form>
      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  )
}
